Repository depromeet/10mm-server, pull requests merged in 2023-11, with the labels that each got.

#2 chore: 프로젝트 세팅
  .editorconfig
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/♻️-refactor.md
  .github/ISSUE_TEMPLATE/⚙️-chore.md
  .github/ISSUE_TEMPLATE/✅-test.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-fix.md
  .github/ISSUE_TEMPLATE/📝-documentation.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/develop_pull_request.yml
  build.gradle
  config/checkstyle/naver-checkstyle-rules.xml
  config/checkstyle/naver-checkstyle-suppressions.xml
  src/main/java/com/depromeet/ExampleController.java
  src/main/java/com/depromeet/TenminuteApplication.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/depromeet/TenMinuteApplicationTests.java
Labels: ⚙️ chore

#4 chore: gradle build action 및 lifecycle 추가
  .github/workflows/develop_pull_request.yml
Labels: ⚙️ chore

#23 fix: CI/CD outputs 변수명 변경
  .github/workflows/develop_build_deploy.yml
Labels: 🐛 bug/error

#19 feat: 커스텀 예외 및 에러 코드/응답 구현
  src/main/java/com/depromeet/global/error/ErrorResponse.java
  src/main/java/com/depromeet/global/error/exception/CustomException.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
Labels: ✨ feature

#28 chore: jacoco 기본 세팅
  build.gradle
Labels: ⚙️ chore
