Repository depromeet/10mm-server, pull requests merged in 2023-12, with the labels that each got.

#34 chore: 성공 응답 공통 처리 어드바이스 생성
  src/main/java/com/depromeet/global/config/response/GlobalResponse.java
  src/main/java/com/depromeet/global/config/response/GlobalResponseAdvice.java
Labels: ⚙️ chore

#6 chore: 프로젝트에 PR 추가 후 status를 '처리대기'로 변경하는 워크플로우 추가
  .github/workflows/project_automation.yml
Labels: ⚙️ chore

#38 chore: 코드 정적 분석 SonarCloud 설정
  .github/workflows/develop_pull_request.yml
  build.gradle
Labels: ⚙️ chore

#58 fix: error 패키지 sonarcloud 테스트 제외
  build.gradle
  lombok.config
Labels: 🐛 bug/error

#45 feat: SpringEnvironmentHelper 생성
  src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
  src/main/java/com/depromeet/global/util/SpringEnvironmentUtil.java
  src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
Labels: ✨ feature, ✅ test

#59 fix: GlobalResponseAdvice 응답 값이 String 타입 예외 처리
  src/main/java/com/depromeet/global/config/response/GlobalResponseAdvice.java
Labels: 🐛 bug/error

#68 fix: Swagger가 안뜨는 문제 해결
  src/main/java/com/depromeet/global/config/response/GlobalResponseAdvice.java
Labels: 🐛 bug/error

#64 feat: Querydsl 환경 구성 추가
  .gitignore
  build.gradle
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/domain/member/domain/Profile.java
  src/main/java/com/depromeet/global/config/QueryDslConfig.java
Labels: ✨ feature

#60 feat: 미션, 미션 기록 도메인 생성
  build.gradle
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/domain/mission/api/.gitkeep
  src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
  src/main/java/com/depromeet/domain/mission/domain/ArchiveStatus.java
  src/main/java/com/depromeet/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/domain/mission/domain/MissionCategory.java
  src/main/java/com/depromeet/domain/mission/domain/MissionVisibility.java
  src/main/java/com/depromeet/domain/mission/dto/.gitkeep
  src/main/java/com/depromeet/domain/mission/exception/.gitkeep
  src/main/java/com/depromeet/domain/mission/service/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/api/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/domain/missionRecord/domain/ImageUploadStatus.java
  src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/domain/missionRecord/dto/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/exception/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/service/.gitkeep
  src/test/java/com/depromeet/domain/mission/domain/MissionTest.java
  src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
Labels: ✨ feature

#63 chore: Global Exception Handler 설정
  src/main/java/com/depromeet/global/error/GlobalExceptionHandler.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
Labels: ⚙️ chore

#71 chore: 공통 상수 Enum으로 관리
  src/main/java/com/depromeet/global/common/constants/EnvironmentConstants.java
  src/main/java/com/depromeet/global/common/constants/UrlConstants.java
  src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
  src/main/java/com/depromeet/global/util/SpringEnvironmentUtil.java
  src/test/java/com/depromeet/global/util/SpringEnvironmentUtilTest.java
Labels: ⚙️ chore

#72 chore: `application.yml` 환경별 분리
  docker-compose.yaml
  src/main/resources/application-actuator.yml
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ⚙️ chore

#79 chore: `develop_deploy.yml`에서 커밋해쉬 사용하도록 수정
  .github/workflows/develop_deploy.yml
Labels: ⚙️ chore

#81 chore: develop_deploy.yml needs 삭제
  .github/workflows/develop_deploy.yml
Labels: ⚙️ chore

#70 fix: Swagger에 Server 리스트 안보이는 문제해결
  src/main/java/com/depromeet/global/config/SwaggerConfig.java
Labels: 🐛 bug/error

#84 feat: 테스트 코드 격리
  src/test/java/com/depromeet/DatabaseCleaner.java
Labels: 🥈 P2, ✅ test

#82 feat: Swagger 접근 거부 문제와 스웨거 보안 기능 추가
  src/main/java/com/depromeet/global/common/constants/SwaggerUrlConstants.java
  src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ feature, 🐛 bug/error
