Repository depromeet/10mm-server, pull requests merged in 2024-05, with the labels that each got.

#392 feat: 알림을 확인 할 수 있는 알림센터 기능 추가
  src/main/java/com/depromeet/domain/notification/api/NotificationController.java
  src/main/java/com/depromeet/domain/notification/application/NotificationService.java
  src/main/java/com/depromeet/domain/notification/dao/NotificationRepository.java
  src/main/java/com/depromeet/domain/notification/dto/NotificationFindAllResponse.java
  src/test/java/com/depromeet/domain/notification/application/NotificationServiceTest.java
Labels: 🥈 P2, ✨ feature

#395 chore: Object Storage -> AWS S3 Bucket 으로 변경
  src/main/java/com/depromeet/domain/image/application/ImageService.java
  src/main/java/com/depromeet/infra/config/properties/PropertiesConfig.java
  src/main/java/com/depromeet/infra/config/s3/S3Config.java
  src/main/java/com/depromeet/infra/config/s3/S3Properties.java
  src/main/resources/application-storage.yml
Labels: ⚙️ chore

#404 fix: QA 반영
  src/main/java/com/depromeet/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/test/java/com/depromeet/domain/feed/application/FeedServiceTest.java
Labels: 🐛 bug/error

#408 v2.0.4
  src/main/java/com/depromeet/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🐛 bug/error, 🌏 deploy
