Repository depromeet/10mm-server, pull requests merged in 2024-01, with the labels that each got.

#77 feat: 미션 서비스 로직 구현 (1차)
  build.gradle
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepository.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/domain/mission/dto/.gitkeep
  src/main/java/com/depromeet/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/domain/mission/dto/request/MissionUpdateRequest.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionCreateResponse.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionUpdateResponse.java
  src/main/java/com/depromeet/domain/mission/service/.gitkeep
  src/main/java/com/depromeet/domain/mission/service/MissionService.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/TestQuerydslConfig.java
  src/test/java/com/depromeet/domain/mission/controller/.gitkeep
  src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
  src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
Labels: ✨ feature

#90 fix: MemberUtilTest에 DatabaseCleaner 적용
  src/test/java/com/depromeet/global/util/MemberUtilTest.java
Labels: 🐛 bug/error

#88 chore: Redis 설정
  .github/workflows/develop_build_deploy.yml
  .github/workflows/develop_pull_request.yml
  build.gradle
  docker-compose-test.yaml
  src/main/java/com/depromeet/infra/.gitkeep
  src/main/java/com/depromeet/infra/config/RedisConfig.java
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
  src/test/java/com/depromeet/TenminuteApplicationTests.java
  src/test/java/com/depromeet/global/util/MemberUtilTest.java
  src/test/resources/application-test.yml
Labels: ⚙️ chore

#94 chore: SecurityConfig 임시로 모든 url 허용
  src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
Labels: 🥉 P3, ⚙️ chore

#97 feat: 미션 기록 저장 기능 구현
  build.gradle
  src/main/java/com/depromeet/domain/missionRecord/api/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/domain/missionRecord/dto/request/MissionRecordCreateRequest.java
  src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
Labels: ✨ feature

#100 chore: NCP Object Storage 설정
  build.gradle
  src/main/java/com/depromeet/infra/config/properties/PropertiesConfig.java
  src/main/java/com/depromeet/infra/config/redis/RedisConfig.java
  src/main/java/com/depromeet/infra/config/redis/RedisProperties.java
  src/main/java/com/depromeet/infra/config/storage/StorageConfig.java
  src/main/java/com/depromeet/infra/config/storage/StorageProperties.java
  src/main/resources/application-storage.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: ⚙️ chore

#111 chore: Swagger Tag 값에 Numbering
  src/main/java/com/depromeet/ExampleController.java
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
Labels: 🥉 P3, ⚙️ chore

#103 test: 미션 Controller 테스트 코드 작성
  src/test/java/com/depromeet/domain/mission/controller/.gitkeep
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
Labels: 🥈 P2, ✅ test

#107 feat: 미션 내역 리스트 조회
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/service/MissionService.java
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepository.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/domain/missionRecord/dto/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
  src/main/java/com/depromeet/domain/missionRecord/service/.gitkeep
  src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
  src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
Labels: 🥇 P1, ✨ feature

#106 feat: PresignedUrl을 사용하여 이미지 업로드 기능 구현
  src/main/java/com/depromeet/domain/image/api/ImageController.java
  src/main/java/com/depromeet/domain/image/application/ImageService.java
  src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
  src/main/java/com/depromeet/domain/image/domain/ImageType.java
  src/main/java/com/depromeet/domain/image/dto/request/MissionRecordImageCreateRequest.java
  src/main/java/com/depromeet/domain/image/dto/request/MissionRecordImageUploadCompleteRequest.java
  src/main/java/com/depromeet/domain/image/dto/response/PresignedUrlResponse.java
  src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/main/java/com/depromeet/infra/config/storage/StorageConfig.java
  src/main/java/com/depromeet/infra/config/storage/StorageProperties.java
  src/main/resources/application-storage.yml
  src/test/java/com/depromeet/domain/image/api/ImageControllerTest.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
  src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
Labels: 🥇 P1, ✨ feature, ✅ test

#116 chore: 공통 응답 포멧 통일
  src/main/java/com/depromeet/ExampleController.java
  src/main/java/com/depromeet/global/common/response/.gitkeep
  src/main/java/com/depromeet/global/common/response/GlobalResponse.java
  src/main/java/com/depromeet/global/common/response/GlobalResponseAdvice.java
  src/main/java/com/depromeet/global/config/querydsl/QueryDslConfig.java
  src/main/java/com/depromeet/global/config/response/GlobalResponse.java
  src/main/java/com/depromeet/global/config/swagger/SwaggerConfig.java
  src/main/java/com/depromeet/global/error/ErrorResponse.java
  src/main/java/com/depromeet/global/error/GlobalExceptionHandler.java
  src/test/java/com/depromeet/domain/image/api/ImageControllerTest.java
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
Labels: 🥈 P2, ⚙️ chore

#114 feat: 미션 인증 및 완료 사진 업로드 단계 예외케이스 처리
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordTTLRepository.java
  src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecordTTL.java
  src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/service/RedisExpireEventRedisMessageListener.java
  src/main/java/com/depromeet/global/common/constants/RedisExpireEventConstants.java
  src/main/java/com/depromeet/infra/config/redis/RedisConfig.java
  src/main/java/com/depromeet/infra/config/redis/RedisMessageListenerConfig.java
Labels: ✨ feature

#128 fix: Redis Expire Event 수신 안되어 docker-compose Redis 사용
  docker-compose.yaml
Labels: 🐛 bug/error

#132 refactor: 미션 기록 생성 응답 값 response 객체로 Wrapping
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordCreateResponse.java
  src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
Labels: 🥉 P3, ♻️ refactor

#136 hotfix: CORS AllowedOrigins 환경 분리
  src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
Labels: 🐛 bug/error

#138 hotfix: CORS문제로 UrlConstants에 www 추가
  src/main/java/com/depromeet/global/common/constants/UrlConstants.java
Labels: 🐛 bug/error

#131 feat: 이미지 업로드 예외케이스에서 업로드 완료시 Redis TTL 삭제 기능
  src/main/java/com/depromeet/domain/image/application/ImageService.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordTTLRepository.java
Labels: 🥇 P1, ✨ feature

#123 feat: 미션 내역 수정 구현
  src/main/java/com/depromeet/domain/mission/dto/request/MissionUpdateRequest.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionUpdateResponse.java
  src/main/java/com/depromeet/domain/mission/service/MissionService.java
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/domain/missionRecord/dto/request/MissionRecordUpdateRequest.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordUpdateResponse.java
  src/main/java/com/depromeet/domain/missionRecord/service/MissionRecordService.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
  src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
Labels: 🥇 P1, ✨ feature

#141 chore: service 패키지를 application으로 변경
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/application/RedisExpireEventRedisMessageListener.java
  src/main/java/com/depromeet/infra/config/redis/RedisMessageListenerConfig.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
  src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
Labels: 🥉 P3, ⚙️ chore

#148 feat: Swagger에 RefresgToekn용 SecuritySchemes 추가
  src/main/java/com/depromeet/global/config/swagger/SwaggerConfig.java
Labels: ✨ feature

#130 feat: 미션 기록 하루에 한개만 처리 가능하도록 기능 추가
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
Labels: 🥇 P1, ✨ feature

#149 fix: 유틸리티에서 픽스처 및 Mock 인증 삽입 로직 제거
  src/main/java/com/depromeet/global/util/MemberUtil.java
  src/main/java/com/depromeet/global/util/SecurityUtil.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
  src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
  src/test/java/com/depromeet/global/util/MemberUtilTest.java
Labels: 🐛 bug/error

#153 feat: 진행중인 미션 제거하는 기능
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
Labels: ✨ feature

#155 feat: 회원 탈퇴 로직 구현
  src/main/java/com/depromeet/domain/auth/api/AuthController.java
  src/main/java/com/depromeet/domain/auth/application/AuthService.java
  src/main/java/com/depromeet/domain/member/api/.gitkeep
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/.gitkeep
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/member/domain/MemberTest.java
Labels: 🥇 P1, ✨ feature

#158 fix: SpringBoot Server TimeZone Asia/Seoul로 설정
  docker-compose.yaml
Labels: 🐛 bug/error

#157 feat: 마이페이지 프로필 사진 수정과 닉네임 변경 기능 구현
  src/main/java/com/depromeet/domain/image/api/ImageController.java
  src/main/java/com/depromeet/domain/image/application/ImageService.java
  src/main/java/com/depromeet/domain/image/dto/request/MemberProfileImageCreateRequest.java
  src/main/java/com/depromeet/domain/image/dto/request/MemberProfileImageUploadCompleteRequest.java
  src/main/java/com/depromeet/domain/image/dto/request/MissionRecordImageUploadCompleteRequest.java
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/domain/member/domain/OauthInfo.java
  src/main/java/com/depromeet/domain/member/domain/Profile.java
  src/main/java/com/depromeet/global/security/CustomOidcUserService.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
  src/test/java/com/depromeet/domain/member/domain/MemberTest.java
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
  src/test/java/com/depromeet/domain/mission/domain/MissionTest.java
  src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
  src/test/java/com/depromeet/domain/missionRecord/domain/MissionRecordTest.java
Labels: ✨ feature

#160 feat: 회원 정보 조회 API
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/domain/member/dto/response/MemberFindOneResponse.java
Labels: ✨ feature

#162 fix: 진행중인 미션기록 삭제할 때 QueryDsl 메소드 사용하도록 변경
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🐛 bug/error

#164 hotfix: develop 서버 CORS 모든 요청 허용으로 변경
  src/main/java/com/depromeet/global/config/security/WebSecurityConfig.java
Labels: 🐛 bug/error

#166 fix: 회원 정보 수정할 때 이미지 nullable 처리
  src/main/java/com/depromeet/domain/image/application/ImageService.java
  src/main/java/com/depromeet/domain/image/dto/request/MemberProfileImageUploadCompleteRequest.java
Labels: 🐛 bug/error

#169 fix: 토큰 만료기간 env로 관리
  src/main/resources/application-security.yml
Labels: 🐛 bug/error

#170 feat: 미션 목록 조회 시 인증필요인 경우 MissionRecordId도 같이 응답
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionFindAllResponse.java
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
Labels: ✨ feature

#176 feat: 닉네임 중복검사
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/domain/member/dto/.gitkeep
  src/main/java/com/depromeet/domain/member/dto/request/NicknameCheckRequest.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
Labels: 🥇 P1, ✨ feature

#179 chore: 프로덕션 배포 워크플로 작성
  .github/workflows/production_build_deploy.yml
  .github/workflows/production_deploy.yml
Labels: ⚙️ chore

#181 feat: 종료미션 DurationStatus 추가 및 스케줄러 구현
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/domain/DurationStatus.java
  src/main/java/com/depromeet/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionFindAllResponse.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
  src/main/java/com/depromeet/global/config/scheduler/SchedulerConfig.java
  src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
  src/main/resources/application-local.yml
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
Labels: 🥇 P1, ✨ feature

#75 feat: 팔로우 도메인 Entity 생성
  src/main/java/com/depromeet/domain/relation/api/.gitkeep
  src/main/java/com/depromeet/domain/relation/application/.gitkeep
  src/main/java/com/depromeet/domain/relation/dao/MemberRelationRepository.java
  src/main/java/com/depromeet/domain/relation/domain/MemberRelation.java
  src/main/java/com/depromeet/domain/relation/dto/.gitkeep
  src/main/java/com/depromeet/domain/relation/exception/.gitkeep
Labels: 🥈 P2, ✨ feature

#177 feat: 전체 미션 통계 현황 API
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordSummaryResponse.java
Labels: 🥇 P1, ✨ feature

#190 fix: 미션 내용 생성/수정할 때 min validate 삭제
  src/main/java/com/depromeet/domain/mission/dto/request/MissionCreateRequest.java
  src/main/java/com/depromeet/domain/mission/dto/request/MissionUpdateRequest.java
Labels: 🐛 bug/error

#184 feat: Swagger 버전 이미지 태그로 동적 추가
  .github/workflows/develop_build_deploy.yml
  .github/workflows/develop_deploy.yml
  .github/workflows/production_build_deploy.yml
  .github/workflows/production_deploy.yml
  src/main/resources/application.yml
Labels: 🥉 P3, ✨ feature

#191 feat: 팔로우 추가 / 취소 기능
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
  src/main/java/com/depromeet/domain/follow/domain/MemberRelation.java
  src/main/java/com/depromeet/domain/follow/dto/request/FollowCreateRequest.java
  src/main/java/com/depromeet/domain/follow/dto/request/FollowDeleteRequest.java
  src/main/java/com/depromeet/domain/follow/exception/.gitkeep
  src/main/java/com/depromeet/domain/relation/application/.gitkeep
  src/main/java/com/depromeet/domain/relation/dao/MemberRelationRepository.java
  src/main/java/com/depromeet/domain/relation/dto/.gitkeep
  src/main/java/com/depromeet/domain/relation/exception/.gitkeep
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/follow/api/FollowControllerTest.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: ✨ feature

#194 fix: totalMissionMinute 계산 수정
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
Labels: 🐛 bug/error

#202 hotfix: 이미지 URL 캐싱 문제로인해 임시로 query 값 추가
  src/main/java/com/depromeet/domain/member/domain/Profile.java
Labels: 🐛 bug/error

#199 feat: 나와 타인의 팔로우/팔로잉 카운트 조회
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
  src/main/java/com/depromeet/domain/follow/domain/MemberRelation.java
  src/main/java/com/depromeet/domain/follow/dto/response/FollowFindMeInfoResponse.java
  src/main/java/com/depromeet/domain/follow/dto/response/FollowFindTargetInfoResponse.java
  src/main/java/com/depromeet/domain/follow/dto/response/FollowStatus.java
  src/main/java/com/depromeet/global/error/GlobalExceptionHandler.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/follow/api/FollowControllerTest.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: ✨ feature

#203 fix: missionRecord -> mission startedAt으로 변경하여 sinceDay 계산 수정
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
Labels: 🥇 P1, 🐛 bug/error

#209 hotfix: Profile Image가 null 일 때 timestamp 안붙도록 처리
  src/main/java/com/depromeet/domain/member/domain/Profile.java
Labels: 🐛 bug/error

#196 feat: 친구 미션 목록
  src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/dto/response/FollowMissionFindAllResponse.java
  src/main/java/com/depromeet/global/util/MemberUtil.java
Labels: 🥇 P1, ✨ feature

#211 fix: request 시 QueryString 아닌 pathVariable targetId로 변경
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/global/util/MemberUtil.java
Labels: 🥇 P1, 🐛 bug/error, ♻️ refactor

#215 feat: 내가 팔로우 한 사용자들 닉네임,프로필 조회
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepositoryCustom.java
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepositoryImpl.java
  src/main/java/com/depromeet/domain/follow/dto/response/MemberFollowedResponse.java
  src/test/java/com/depromeet/domain/follow/api/FollowControllerTest.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: ✨ feature, ✅ test

#216 refactor: Build시 appleboy/scp-action@v0.1.4 속도 개선
  .github/workflows/develop_build_deploy.yml
  .github/workflows/production_build_deploy.yml
Labels: ♻️ refactor

#221 fix: 통계 현황에서 총 미션 달성률 항상 100% 나오는 문제
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
Labels: 🥇 P1, 🐛 bug/error

#225 feat: 닉네임 검색 기능
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepository.java
  src/main/java/com/depromeet/domain/follow/domain/MemberRelation.java
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/domain/member/dto/response/MemberSearchResponse.java
  src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
Labels: ✨ feature, ✅ test

#227 feat: 번개 스택 조회
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionSymbolStackResponse.java
Labels: 🥇 P1, ✨ feature

#226 refactor: Image 업로드 시 ImageKey 관리
  src/main/java/com/depromeet/domain/image/application/ImageService.java
  src/main/java/com/depromeet/domain/image/dao/ImageRepository.java
  src/main/java/com/depromeet/domain/image/domain/Image.java
  src/main/java/com/depromeet/domain/member/domain/Profile.java
  src/main/java/com/depromeet/global/common/constants/UrlConstants.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
Labels: ♻️ refactor

#229 hotfix: 회원 정보 조회 시 ImageFileExtension도 같이 응답하도록 수정
  src/main/java/com/depromeet/domain/image/domain/ImageFileExtension.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/dto/response/MemberFindOneResponse.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
Labels: 🐛 bug/error

#234 feat: 타인 member 정보 조회
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
Labels: 🥇 P1, ✨ feature

#235 hotfix: 회원 프로필 이미지 변경 PresignedUrl 발급 시 이미지 키 생성
  src/main/java/com/depromeet/domain/image/application/ImageService.java
Labels: 🐛 bug/error

#248 fix: 미션 리스트 조회 시 InProgress인 미션만 조회로 변경
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
Labels: 🥇 P1, 🐛 bug/error

#252 feat: 캘린더 뷰 조회 응답에 미션 시작 시간, 끝 시간을 추가
  src/main/java/com/depromeet/domain/missionRecord/api/MissionRecordController.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindResponse.java
Labels: ✨ feature

#254 fix: 닉네임 조회 시 팔로우 상태 버그 수정
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
Labels: 🐛 bug/error

#260 feat: FCM 기능 추가
  build.gradle
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/domain/FcmInfo.java
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/domain/member/dto/request/UpdateFcmTokenRequest.java
  src/main/java/com/depromeet/domain/notification/api/.gitkeep
  src/main/java/com/depromeet/domain/notification/application/.gitkeep
  src/main/java/com/depromeet/domain/notification/dao/.gitkeep
  src/main/java/com/depromeet/domain/notification/domain/.gitkeep
  src/main/java/com/depromeet/domain/notification/dto/.gitkeep
  src/main/java/com/depromeet/global/config/fcm/FcmConfig.java
  src/main/java/com/depromeet/global/config/fcm/FcmService.java
  src/main/resources/application.yml
Labels: 🥇 P1, ✨ feature

#263 feat: 필요한 이벤트에 FCM 푸시 알림 추가
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/notification/application/NotificationService.java
  src/main/java/com/depromeet/domain/notification/dao/.gitkeep
  src/main/java/com/depromeet/domain/notification/dao/NotificationRepository.java
  src/main/java/com/depromeet/domain/notification/domain/.gitkeep
  src/main/java/com/depromeet/domain/notification/domain/Notification.java
  src/main/java/com/depromeet/domain/notification/domain/NotificationType.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: 🥇 P1, ✨ feature

#265 fix: Member Entity Fcminfo 변경감지 수정
  src/main/java/com/depromeet/domain/member/domain/Member.java
Labels: 🥇 P1, 🐛 bug/error
