Repository depromeet/10mm-server, pull requests merged in 2024-02, with the labels that each got.

#267 fix: nickname 검색 예외 처리 (escape)
  src/main/java/com/depromeet/domain/member/api/MemberController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/domain/member/domain/Profile.java
  src/main/java/com/depromeet/domain/notification/application/.gitkeep
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
Labels: 🥇 P1, 🐛 bug/error

#274 feat: 유저 팔로잉/팔로워 목록 조회 API
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/follow/dto/response/FollowListResponse.java
Labels: ✨ feature

#279 fix: fcm 토큰이 빈 값이라면 푸시 알림을 보내지 않도록 설정
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/member/domain/FcmInfo.java
  src/main/java/com/depromeet/domain/member/domain/Member.java
  src/main/java/com/depromeet/global/config/fcm/FcmService.java
Labels: 🐛 bug/error

#277 feat: 피드 탭 구현
  src/main/java/com/depromeet/domain/feed/api/FeedController.java
  src/main/java/com/depromeet/domain/feed/application/FeedService.java
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneResponse.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/follow/dao/MemberRelationRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryCustom.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
  src/main/resources/application-local.yml
Labels: 🥇 P1, ✨ feature

#287 feat: 내 팔로워 목록 중 선택한 유저 내 팔로워에서 지우기
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/follow/dto/response/FollowerDeletedResponse.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: 🥇 P1, ✨ feature

#289 hotfix: 푸시 알림 시 닉네임이 username이 아닌 nickname을 사용하도록 변경(main)
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
Labels: 🐛 bug/error

#290 hotfix: 푸시 알림 시 닉네임이 username이 아닌 nickname을 사용하도록 변경(develop)
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
Labels: 🐛 bug/error

#286 팔로우 취소 시 알림 히스토리 삭제
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/notification/api/.gitkeep
  src/main/java/com/depromeet/domain/notification/application/NotificationService.java
  src/main/java/com/depromeet/domain/notification/dao/NotificationRepository.java
  src/main/java/com/depromeet/domain/notification/dto/.gitkeep
Labels: 🥈 P2, 🐛 bug/error

#178 feat: 종료미션 보관함 API 구현
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/dto/response/FinishedMissionResponse.java
Labels: 🥇 P1, ✨ feature

#296 feat: 팔로우 취소 시 상대의 팔로우 상태 응답하도록 변경
  src/main/java/com/depromeet/domain/follow/api/FollowController.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: ✨ feature

#300 feat: Retension 이벤트 푸시 알림
  src/main/java/com/depromeet/domain/common/constants/PushNotificationConstants.java
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepositoryCustom.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepositoryImpl.java
  src/main/java/com/depromeet/scheduler/member/MemberBatchScheduler.java
Labels: 🥇 P1, ✨ feature

#304 feat: 미션 단건조회 응답 값에 미션 시작시간과 끝나는 시간 추가
  src/main/java/com/depromeet/domain/mission/dto/response/MissionFindResponse.java
  src/test/java/com/depromeet/domain/mission/controller/MissionControllerTest.java
Labels: ✨ feature

#308 hotfix: 피드 Response에 미션 시작한지 N일차(sinceDay) 데이터 값이 올바르게 나오지 않는 버그
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
Labels: 🐛 bug/error

#309 feat: 친구가 당일 미션을 완료하지 않은 경우 재촉하기
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordCalendarResponse.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/UrgingStatus.java
  src/main/java/com/depromeet/domain/notification/api/PushController.java
  src/main/java/com/depromeet/domain/notification/application/FcmService.java
  src/main/java/com/depromeet/domain/notification/application/PushService.java
  src/main/java/com/depromeet/domain/notification/domain/NotificationType.java
  src/main/java/com/depromeet/domain/notification/dto/request/PushUrgingSendRequest.java
  src/main/java/com/depromeet/global/common/constants/PushNotificationConstants.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/main/java/com/depromeet/infra/config/fcm/FcmConfig.java
  src/test/java/com/depromeet/domain/notification/application/PushServiceTest.java
Labels: ✨ feature

#313 fix: 미션 n일차 표기 수정
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🥇 P1, 🐛 bug/error

#319 fix: 본인이 본인을 팔로우하는 경우 Validation 추가
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
Labels: 🐛 bug/error

#315 feat: 미션 전체 현황 - 날짜로 미션 목록 조회
  src/main/java/com/depromeet/domain/mission/api/MissionController.java
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionSummaryItem.java
  src/main/java/com/depromeet/domain/mission/dto/response/MissionSummaryListResponse.java
Labels: ✨ feature

#322 fix: 친구 미션 목록 in-progress 조건 추가
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
Labels: 🥇 P1, 🐛 bug/error

#324 hotfix: 통계 미션 목록 조회 날짜 비교 추가
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
Labels: 🐛 bug/error

#330 fix: sinceDay 정의
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneResponse.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🥇 P1, 🐛 bug/error

#334 feat: 리액션 추가 시 푸시 메세지 발송
  src/main/java/com/depromeet/domain/notification/domain/NotificationType.java
  src/main/java/com/depromeet/domain/reaction/application/ReactionService.java
  src/main/java/com/depromeet/global/common/constants/PushNotificationConstants.java
Labels: ✨ feature

#336 docs: README.md 작성
  README.md
Labels: 📝 documentation

#333 fix: 종료미션의 경우 재촉하기 불가능하도록 검증 추가
  src/main/java/com/depromeet/domain/mission/domain/Mission.java
  src/main/java/com/depromeet/domain/notification/application/PushService.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
  src/test/java/com/depromeet/domain/notification/application/PushServiceTest.java
Labels: 🐛 bug/error

#341 fix: 통계 연속 일자 수정
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneResponse.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🥇 P1, 🐛 bug/error

#342 fix: 미션 전체 현황 날짜 조건 수정
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
Labels: 🥇 P1, 🐛 bug/error

#344 feat: 미션 기록 조회 시 COMPLETE 일때 missionRecordId 추가
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
Labels: ✨ feature

#346 fix: 미션 전체 현황 처리 (Date 포맷으로 해결)
  src/main/java/com/depromeet/domain/mission/application/MissionService.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
Labels: 🥇 P1, 🐛 bug/error

#349 fix: sinceDay 계산 로직 변경
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneByProfileResponse.java
  src/main/java/com/depromeet/domain/feed/dto/response/FeedOneResponse.java
  src/main/java/com/depromeet/domain/missionRecord/application/MissionRecordService.java
  src/main/java/com/depromeet/domain/missionRecord/dto/response/MissionRecordFindOneResponse.java
  src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
Labels: 🐛 bug/error

#352 fix: 피드 record finishedAt 내림차순으로 정렬
  src/main/java/com/depromeet/domain/missionRecord/dao/MissionRecordRepositoryImpl.java
Labels: 🐛 bug/error
