Repository depromeet/10mm-server, pull requests merged in 2024-06, with the labels that each got.

#391 feat: 랭킹 API 구현
  src/main/java/com/depromeet/domain/comment/api/CommentController.java
  src/main/java/com/depromeet/domain/member/application/MemberService.java
  src/main/java/com/depromeet/domain/member/dao/MemberRepository.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryCustom.java
  src/main/java/com/depromeet/domain/mission/dao/MissionRepositoryImpl.java
  src/main/java/com/depromeet/domain/missionRecord/domain/MissionRecord.java
  src/main/java/com/depromeet/domain/ranking/api/RankingController.java
  src/main/java/com/depromeet/domain/ranking/application/RankingService.java
  src/main/java/com/depromeet/domain/ranking/dao/RankingRepository.java
  src/main/java/com/depromeet/domain/ranking/domain/Ranking.java
  src/main/java/com/depromeet/domain/ranking/dto/RankingDto.java
  src/main/java/com/depromeet/domain/ranking/dto/response/RankingResponse.java
  src/main/java/com/depromeet/global/common/constants/PushNotificationConstants.java
  src/main/java/com/depromeet/scheduler/mission/MissionBatchScheduler.java
  src/test/java/com/depromeet/domain/ranking/application/RankingServiceTest.java
Labels: 🥈 P2, ✨ feature

#389 test: Database cleaner 리팩토링
  src/test/java/com/depromeet/DatabaseCleaner.java
  src/test/java/com/depromeet/NoTransactionExtension.java
  src/test/java/com/depromeet/domain/comment/application/CommentServiceTest.java
  src/test/java/com/depromeet/domain/feed/application/FeedServiceTest.java
  src/test/java/com/depromeet/domain/follow/application/FollowServiceTest.java
  src/test/java/com/depromeet/domain/image/application/ImageServiceTest.java
  src/test/java/com/depromeet/domain/member/application/MemberServiceTest.java
  src/test/java/com/depromeet/domain/mission/repository/MissionRepositoryTest.java
  src/test/java/com/depromeet/domain/mission/service/MissionServiceTest.java
  src/test/java/com/depromeet/domain/missionRecord/application/MissionRecordServiceTest.java
  src/test/java/com/depromeet/domain/notification/application/NotificationServiceTest.java
  src/test/java/com/depromeet/domain/ranking/application/RankingServiceTest.java
  src/test/java/com/depromeet/domain/reaction/application/ReactionServiceTest.java
  src/test/java/com/depromeet/global/util/MemberUtilTest.java
  src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  src/test/resources/junit-platform.properties
Labels: 🥉 P3, ✅ test

#410 feat: 알림센터 Message추가와 클릭 시 대상으로 이동할 수 있도록 자원 ID와 추가
  src/main/java/com/depromeet/domain/follow/application/FollowService.java
  src/main/java/com/depromeet/domain/notification/application/NotificationService.java
  src/main/java/com/depromeet/domain/notification/domain/Notification.java
  src/main/java/com/depromeet/domain/notification/dto/NotificationFindAllResponse.java
  src/main/java/com/depromeet/global/error/exception/ErrorCode.java
Labels: ✨ feature

#412 chore: pre-commit 시 spotlessApply 실행
  build.gradle
  scripts/pre-commit
Labels: 🥉 P3, ⚙️ chore
